// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY8clXAp84_5e1mtN5rDu6P8-vvR9c-4Y',
    appId: '1:663356532451:web:4093389f9d506c24db47d6',
    messagingSenderId: '663356532451',
    projectId: 'tum-ai',
    authDomain: 'tum-ai.firebaseapp.com',
    storageBucket: 'tum-ai.appspot.com',
    measurementId: 'G-PJYVGL38JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXQN_laj0e5G6toMdbkYTbnGboJKtxBW0',
    appId: '1:663356532451:android:56de0b88003a518edb47d6',
    messagingSenderId: '663356532451',
    projectId: 'tum-ai',
    storageBucket: 'tum-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYv4QOfusqEZNV421ZVIjPrH461wMFZz8',
    appId: '1:663356532451:ios:7ab1c6c499844365db47d6',
    messagingSenderId: '663356532451',
    projectId: 'tum-ai',
    storageBucket: 'tum-ai.appspot.com',
    iosBundleId: 'com.example.tumAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYv4QOfusqEZNV421ZVIjPrH461wMFZz8',
    appId: '1:663356532451:ios:7ab1c6c499844365db47d6',
    messagingSenderId: '663356532451',
    projectId: 'tum-ai',
    storageBucket: 'tum-ai.appspot.com',
    iosBundleId: 'com.example.tumAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY8clXAp84_5e1mtN5rDu6P8-vvR9c-4Y',
    appId: '1:663356532451:web:741f1a7a312f7a9cdb47d6',
    messagingSenderId: '663356532451',
    projectId: 'tum-ai',
    authDomain: 'tum-ai.firebaseapp.com',
    storageBucket: 'tum-ai.appspot.com',
    measurementId: 'G-GVF70N3JYF',
  );
}
